export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const LOAD_ADDRESSES_SUCCESS = "LOAD_ADDRESSES_SUCCESS";

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";
